routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('/cotizador');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('users', 'UserController');

Route::resource('biens', 'BienController');

Route::resource('tasas', 'TasaController');

Route::resource('valorTasas', 'ValorTasaController');

Route::resource('cotizacions', 'CotizacionController');

Route::get('pdf/{id}',['as' => 'crearPDF', 'uses' => 'CotizacionController@crearPDF']);

Route::get('verpdf/{id}',['as' => 'pdf', 'uses' => 'CotizacionController@pdf']);

Route::get('cotizaciones/web',['as' => 'cotizacionesWeb', 'uses' => 'CotizacionController@cotizacionesWeb']);

Route::get('/cotizador', 'FrontController@index');

Route::post('enviarCotizacion',['as' => 'front.enviar_cotizacion', 'uses' => 'FrontController@enviar_cotizacion']);

Route::get('/getValores/{id}',['as' => 'getValores', 'uses' => 'TasaController@getValores']);

Route::get('hola',['as' => 'front.info', 'uses' => 'FrontController@phpinfo']);

app/Models/ValorTasa.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ValorTasa
 * @package App\Models
 * @version November 9, 2018, 6:06 pm UTC
 *
 * @property \App\Models\Tasa tasa
 * @property \Illuminate\Database\Eloquent\Collection cotizaciones
 * @property integer tasa_id
 * @property decimal valor
 */
class ValorTasa extends Model
{
    use SoftDeletes;

    public $table = 'valoresTasas';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'tasa_id',
        'valor'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'tasa_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function tasa()
    {
        return $this->belongsTo(\App\Models\Tasa::class);
    }
}

app/Http/Controllers/ValorTasaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateValorTasaRequest;
use App\Http\Requests\UpdateValorTasaRequest;
use App\Repositories\ValorTasaRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class ValorTasaController extends AppBaseController
{
    /** @var  ValorTasaRepository */
    private $valorTasaRepository;

    public function __construct(ValorTasaRepository $valorTasaRepo)
    {
        $this->valorTasaRepository = $valorTasaRepo;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the ValorTasa.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->valorTasaRepository->pushCriteria(new RequestCriteria($request));
        $valorTasas = $this->valorTasaRepository->all();

        return view('valor_tasas.index')
            ->with('valorTasas', $valorTasas);
    }

    /**
     * Show the form for creating a new ValorTasa.
     *
     * @return Response
     */
    public function create()
    {
        $valorTasa = 'NULL';
        return view('valor_tasas.create')->with('valorTasa',$valorTasa);
    }

    /**
     * Store a newly created ValorTasa in storage.
     *
     * @param CreateValorTasaRequest $request
     *
     * @return Response
     */
    public function store(CreateValorTasaRequest $request)
    {
        $new_valor = new \App\Models\ValorTasa();        

        $const="";
        foreach($request->bien_section as $var)
        {
            $const.=','.($var);
        }
        $const = trim($const, ',');

        if($request->plazo_vr != null)
        {
            $aux = "";
            foreach($request->plazo_vr as $var)
            {
                $aux.=','.($var);
            }
            $aux = trim($aux,',');

            $new_valor->plazo_vr = $aux;
        }
        else{

        }
        
        $new_valor->tasa_id = $request->tasa;
        $new_valor->valor = $request->valor;
        $new_valor->bien_section = $const;
        $new_valor->save();

        Flash::success('Valor agregado a la tasa');

        return redirect(route('valorTasas.index'));
    }

    /**
     * Display the specified ValorTasa.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $valorTasa = $this->valorTasaRepository->findWithoutFail($id);

        if (empty($valorTasa)) {
            Flash::error('Valor Tasa not found');

            return redirect(route('valorTasas.index'));
        }

        return view('valor_tasas.show')->with('valorTasa', $valorTasa);
    }

    /**
     * Show the form for editing the specified ValorTasa.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $valorTasa = $this->valorTasaRepository->findWithoutFail($id);

        if (empty($valorTasa)) {
            Flash::error('Valor Tasa not found');

            return redirect(route('valorTasas.index'));
        }

        return view('valor_tasas.edit')->with('valorTasa', $valorTasa);
    }

    /**
     * Update the specified ValorTasa in storage.
     *
     * @param  int              $id
     * @param UpdateValorTasaRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateValorTasaRequest $request)
    {
        
        $valorTasa = \App\Models\ValorTasa::find($id);
        
        if (empty($valorTasa)) {
            Flash::error('Valor Tasa not found');

            return redirect(route('valorTasas.index'));
        } 

        $const="";
        foreach($request->bien_section as $var)
        {
            $const.=','.($var);
        }
        $const = trim($const, ',');
        
        if($request->plazo_vr != null)
        {
            $aux="";
            foreach($request->plazo_vr as $variable)
            {
                $aux.=','.($variable);
            }
            $aux = trim($aux,',');
            
            $valorTasa->plazo_vr = $aux;
        }
        else{

        }

        $valorTasa->tasa_id = $request->tasaIDupdate;
        $valorTasa->valor = $request->valor;
        $valorTasa->bien_section = $const;
        $valorTasa->save();

        Flash::success('Valor de la tasa actualizado');

        return redirect(route('valorTasas.index'));
    }

    /**
     * Remove the specified ValorTasa from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $valorTasa = $this->valorTasaRepository->findWithoutFail($id);

        if (empty($valorTasa)) {
            Flash::error('Valor Tasa not found');

            return redirect(route('valorTasas.index'));
        }

        $this->valorTasaRepository->delete($id);

        Flash::success('Valor de la tasa eliminado');

        return redirect(route('valorTasas.index'));
    }
}

resources/views/valor_tasas/create.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <!-- Valor Tasa -->
        </h1>
    </section>
    <div class="content" style="width:100%">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    <div class="main-content-container container-fluid px-4">
                        {!! Form::open(['route' => 'valorTasas.store']) !!}

                            @include('valor_tasas.fields')

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#bien-table').DataTable({
            responsive: true,
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json' //Ubicacion del archivo con el json del idioma.
            }
        
        });
        $('#plazoResidual').DataTable({
            responsive: true,
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json' //Ubicacion del archivo con el json del idioma.
            }
        
        });
    });

    function tipoBien(dato)
        {
            if(dato == 5)
            {
                $('#vr_campo').show();
            }
            else{
                $('#vr_campo').hide();                
            }
        }
</script>
@endsection

resources/views/valor_tasas/edit.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <!-- Valor Tasa -->
        </h1>
   </section>
   <div class="content" style="width:100%">   
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                    <div class="main-content-container container-fluid px-4">
                        {!! Form::model($valorTasa, ['route' => ['valorTasas.update', $valorTasa->id], 'method' => 'patch']) !!}

                                @include('valor_tasas.fields')

                        {!! Form::close() !!}
                    </div>
               </div>
           </div>
       </div>
   </div>
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#bien-table').DataTable({
            responsive: true,
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json' //Ubicacion del archivo con el json del idioma.
            }
        
        });
        $('#plazoResidual').DataTable({
            responsive: true,
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json' //Ubicacion del archivo con el json del idioma.
            }
        
        });
        
    });
</script>
@endsection

resources/views/valor_tasas/fields.blade.php
<?php
$tasas = \App\Models\Tasa::all();
$bienes = \App\Models\Bien::all();
$plazos = \App\Models\ValorTasa::where('tasa_id','=',2)->get();

$bandera = 0;
$bandera2 = 0;
if($valorTasa != "NULL")
{
    $section_array = explode(",", $valorTasa->bien_section);
    $plazo_array = explode(",", $valorTasa->plazo_vr);
}
else{
    
}
?>
<div class="form-group col-sm-12">
    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Valor de la tasa</span>
        <h3 class="page-title">Llene el formulario con los datos solicitados</h3>
        </div>
    </div>
</div>
<div class="form-group col-sm-12 row">
    <!-- Tasa Id Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('tasa_id', 'Tasa:') !!}
        <select class="form-control" id="selectTasas" name="tasa" onchange="tipoBien(this.value)">
            <option value="" disabled selected>Selecciona una tasa</option>
            @if($valorTasa != "NULL")    
                @foreach($tasas as $tasa)     
                        <option value='{!! $tasa->id !!}' @if($valorTasa->tasa_id == $tasa->id) selected @endif disabled>{!! $tasa->nombre !!}</option>
                @endforeach
            @else
                @foreach($tasas as $tasa)     
                    @if($tasa->id == 3 || $tasa->id == 4 || $tasa->id == 6 || $tasa->id == 7)
                    @else
                    <option value='{!! $tasa->id !!}'>{!! $tasa->nombre !!}</option>
                    @endif
                @endforeach
            @endif
        </select>  
    </div>
    @if($valorTasa != "NULL")
        @if($valorTasa->tasa_id != null)
        {!! Form::hidden('tasaIDupdate', $valorTasa->tasa_id, ['class' => 'form-control']) !!}
        @endif
    @endif
    <!-- Valor Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('valor', 'Valor:') !!}
        {!! Form::number('valor', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group col-sm-12">
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
            <span class="text-uppercase page-subtitle">Selección de bienes</span>
            <h3 class="page-title">Marque los bienes a los cuales correspondera este valor</h3>
            </div>
        </div>
    </div>

    <!-- bien_section field -->
    <div class="form-group col-sm-12">
        <table class="table table-responsive-sm" id="bien-table">
            <thead>
                <tr>          
                    <th>Disponible para</th>
                    <th>Marcar</th>
                </tr>
            </thead>
            <tbody>
            @if($valorTasa != "NULL")    
                @foreach($bienes as $bien)
                    @foreach($section_array as $sa)
                        @if($bien->nombre == $sa)
                            <?php $bandera = 1;?>
                        @endif
                    @endforeach                    
                    @if($bandera == 1)
                        <tr>
                            <td>{!! $bien->nombre !!}</td>
                            <td><input type="checkbox"  name="bien_section[]" value="{!! $bien->nombre !!}" checked class="form-check-input"></td>        
                        </tr>
                    @else
                        <tr>
                            <td>{!! $bien->nombre !!}</td>
                            <td><input type="checkbox"  name="bien_section[]" value="{!! $bien->nombre !!}" class="form-check-input"></td>        
                        </tr>
                    @endif
                    <?php $bandera = 0;?>
                @endforeach
            @else
                @foreach($bienes as $bien)
                    <tr>
                        <td>{!! $bien->nombre !!}</td>
                        <td><input type="checkbox"  name="bien_section[]" value="{!! $bien->nombre !!}" class="form-check-input"></td>        
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
    </div>
    @if($valorTasa != "NULL" && $valorTasa->tasa_id == 5)   
    <div class="form-group col-sm-12" id="vr_campo">
    @else
    <div class="form-group col-sm-12" id="vr_campo" style="display:none">
    @endif
        <div class="form-group col-sm-12">
            <div class="page-header row no-gutters py-4">
                <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Selección de plazo para valor residual</span>
                <h3 class="page-title">Marque el plazo que corresponde al valor residual</h3>
                </div>
            </div>
        </div>

        <div class="form-group col-sm-12">
            <table class="table table-responsive" id="plazoResidual">
                <thead>
                    <tr>
                        <th>Disponible para</th>
                        <th>Marcar</th>
                    </tr>
                </thead>
                <tbody>
                @if($valorTasa != "NULL")
                    @foreach($plazos as $p)
                        @foreach($plazo_array as $pa)
                            @if($p->valor == $pa)
                            <?php $bandera2 = 1?>
                            @endif
                        @endforeach
                        @if($bandera2 == 1)
                        <tr>
                            <td>{!! $p->valor !!} meses</td>
                            <td><input type="checkbox"  name="plazo_vr[]" value="{!! $p->valor !!}" checked class="form-check-input"></td>
                        </tr>
                        @else
                        <tr>
                            <td>{!! $p->valor !!} meses</td>
                            <td><input type="checkbox"  name="plazo_vr[]" value="{!! $p->valor !!}" class="form-check-input"></td>
                        </tr>
                        @endif
                        <?php $bandera = 0;?>
                    @endforeach
                @else
                    @foreach($plazos as $p)
                        <tr>
                            <td>{!! $p->valor !!} meses</td>
                            <td><input type="checkbox"  name="plazo_vr[]" value="{!! $p->valor !!}" class="form-check-input"></td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
    </div>
    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('valorTasas.index') !!}" class="btn btn-secondary">Cancelar</a>
    </div>
</div> 

resources/views/valor_tasas/index.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
@endsection

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Ajuste de valores</h1>
        <h1 class="pull-right">
           <!-- <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('valorTasas.create') !!}">Agregar nuevo valor</a> -->
           <br>
        </h1>
    </section>
    <div class="form-group col-sm-12" style="style="padding-right: 0px; padding-left: 0px;"">
        @include('flash::message')
        <div class="form-group col-sm-12">            
            @include('valor_tasas.table')
        </div>
        
        <div class="text-center">
        
        </div>
    </div>
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#valorTasas-table').DataTable({
            responsive: true,
            "order": [[ 0, 'asc' ]],
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json' //Ubicacion del archivo con el json del idioma.
            }
        
        });
    });
</script>
@endsection

resources/views/valor_tasas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Valor Tasa
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('valor_tasas.show_fields')
                    <a href="{!! route('valorTasas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/valor_tasas/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $valorTasa->id !!}</p>
</div>

<!-- Tasa Id Field -->
<div class="form-group">
    {!! Form::label('tasa_id', 'Tasa Id:') !!}
    <p>{!! $valorTasa->tasa_id !!}</p>
</div>

<!-- Valor Field -->
<div class="form-group">
    {!! Form::label('valor', 'Valor:') !!}
    <p>{!! $valorTasa->valor !!}</p>
</div>

resources/views/valor_tasas/table.blade.php
<table class="table table-responsive-sm" id="valorTasas-table">
    <thead>
        <tr>
        <th>Tasa</th>
        <th>Valor</th>
        <th>Disponible para</th>
        <th>Aplica en</th>
        <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
    @foreach($valorTasas as $valorTasa)
    <?php
    $array_bien = explode(",", $valorTasa->bien_section);    
    ?>
        <tr>
            <td>{!! $valorTasa->tasa->nombre !!}</td>
            <td>
                @if($valorTasa->tasa_id == 1 || $valorTasa->tasa_id == 3 || $valorTasa->tasa_id == 4 || $valorTasa->tasa_id == 5 || $valorTasa->tasa_id == 6)
                    {!! $valorTasa->valor !!}% 
                @elseif($valorTasa->tasa_id == 2)
                    {!! $valorTasa->valor !!} meses
                @elseif($valorTasa->tasa_id == 7)
                    ${!! $valorTasa->valor !!}
                @endif
            </td>
            <td>
            @foreach($array_bien as $bien)
            <ul>
                <li>{!! $bien !!}</li>
            </ul>
            @endforeach
            </td>
            <td>
            @if($valorTasa->plazo_vr != null)
            {!! $valorTasa->plazo_vr !!} meses
            @else
            Todos los meses
            @endif
            </td>
            <td>
                {!! Form::open(['route' => ['valorTasas.destroy', $valorTasa->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('valorTasas.edit', [$valorTasa->id]) !!}" class='btn btn-primary btn-xs'><i class="far fa-edit"></i></a>
                    <!-- {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Esta seguro de eliminar el valor de esta tasa?')"]) !!} -->
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>