routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('/cotizador');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('users', 'UserController');

Route::resource('biens', 'BienController');

Route::resource('tasas', 'TasaController');

Route::resource('valorTasas', 'ValorTasaController');

Route::resource('cotizacions', 'CotizacionController');

Route::get('pdf/{id}',['as' => 'crearPDF', 'uses' => 'CotizacionController@crearPDF']);

Route::get('verpdf/{id}',['as' => 'pdf', 'uses' => 'CotizacionController@pdf']);

Route::get('cotizaciones/web',['as' => 'cotizacionesWeb', 'uses' => 'CotizacionController@cotizacionesWeb']);

Route::get('/cotizador', 'FrontController@index');

Route::post('enviarCotizacion',['as' => 'front.enviar_cotizacion', 'uses' => 'FrontController@enviar_cotizacion']);

Route::get('/getValores/{id}',['as' => 'getValores', 'uses' => 'TasaController@getValores']);

Route::get('hola',['as' => 'front.info', 'uses' => 'FrontController@phpinfo']);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Cotizador Proleasing - Administrador</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="icon" type="image/png" href="{!! asset('imagenes/favicon.ico') !!}" />
    <!-- <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/css/skins/_all-skins.min.css"> -->

    <!-- Ionicons -->
    <!-- <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css"> -->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="{!! asset('assets/styles/shards-dashboards.1.1.0.min.css') !!}">
    <link rel="stylesheet" href="{!! asset('assets/styles/extras.1.1.0.min.css') !!}">
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    @yield('css')
</head>


<body class="h-100">
<div class="">
    <!-- Main Header -->
    <header class="main-header">

        <!-- Logo -->
        
    </header>

    <!-- Left side column. contains the logo and sidebar -->
<div class="container-fluid">
    <div class="row">
        @include('layouts.sidebar')
        <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
            <div class="main-navbar sticky-top bg-white">
            
                <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
                    <form action="#" class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">
                    
                    </form>
                    <ul class="navbar-nav border-left flex-row ">            
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle mr-2" src="{!! asset('imagenes/logo-proleasing.png') !!}" alt="User Avatar">
                            <span class="d-none d-md-inline-block">{!! Auth::user()->name !!}</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-small">
                            <a class="dropdown-item text-danger" href="{!! url('/logout') !!}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"">
                                <i class="material-icons text-danger">&#xE879;</i> Cerrar sesión </a>
                            </div>
                            <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                    <nav class="nav">
                    <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
                        <i class="material-icons">&#xE5D2;</i>
                    </a>
                    </nav>
                </nav>
            </div>
<!-- Content Wrapper. Contains page content -->
            <div class="main-content-container container-fluid px-4">
                <div class="row">                    
                    @yield('content')
                </div>
            </div>
        </main>
    </div>

    <!-- Main Footer -->
    <footer class="main-footer d-flex p-2 px-3 bg-white border-top">
        <span class="copyright ml-auto my-auto mr-2">Derechos reservados © 2018
            <a href="http://birdev.mx" rel="nofollow">Birdev</a>
        </span>
    </footer>
</div>


<!-- jQuery 3.1.1 -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script> -->

<!-- AdminLTE App -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/js/app.min.js"></script> -->

<!-- SCRIPTS DEL TEMA -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
<script src="{!! asset('assets/scripts/extras.1.1.0.min.js') !!}"></script>
<script src="{!! asset('assets/scripts/shards-dashboards.1.1.0.min.js') !!}"></script>

<!-- <script src="{!! asset('assets/scripts/app/app-blog-overview.1.1.0.js') !!}"></script> -->



@yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<li class="nav-item">
<a class="{{ Request::is('cotizacions*') ? 'nav-link active' : 'nav-link' }}" href="{!! route('cotizacions.index') !!}">
    <i class="material-icons">edit</i>
    <span>Cotizaciones</span>
</a>
</li>
<?php
$user = Auth::user();
?>
@if($user->tipo_user == "Administrador")

<li class="nav-item">
<a class="{{ Request::is('cotizaciones*') ? 'nav-link active' : 'nav-link' }}" href="{!! asset('cotizaciones/web') !!}">
    <i class="material-icons">laptop</i>
    <span>Cotzaciones Web</span>
</a>
</li>

<li class="nav-item">
<a class="{{ Request::is('users*') ? 'nav-link active' : 'nav-link' }} " href="{!! route('users.index') !!}">
    <i class="material-icons">vertical_split</i>
    <span>Usuarios</span>
</a>
</li>

<li class="nav-item">
<a class="{{ Request::is('valorTasas*') ? 'nav-link active' : 'nav-link' }}" href="{!! route('valorTasas.index') !!}">
    <i class="material-icons">table_chart</i>
    <span>Ajuste de tasas</span>
</a>
</li>       
@else
@endif

resources/views/layouts/sidebar.blade.php
<!-- <aside class="main-sidebar" id="sidebar-wrapper"> -->

    <!-- sidebar: style can be found in sidebar.less -->
    <!-- <section class="sidebar"> -->

        <!-- Sidebar user panel (optional) -->
        <!-- <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif -->
                <!-- Status -->
                <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div> -->

        <!-- search form (Optional) -->
        <!-- <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form> -->
        <!-- Sidebar Menu -->

        <!-- <ul class="sidebar-menu">
            @include('layouts.menu')
        </ul> -->
        <!-- /.sidebar-menu -->
    <!-- </section> -->
    <!-- /.sidebar -->
<!-- </aside> -->

<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0" style="background-color: #212529 !important;">
            <a class="navbar-brand w-100 mr-0" href="http://www.pro-leasing.mx/" style="line-height: 25px;">
            <div class="d-table m-auto">
                <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 100%;" src="{!! asset('imagenes/logo.png') !!}" alt="Shards Dashboard">
                <!-- <span class="d-none d-md-inline ml-1">Proleasing</span> -->
            </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
            <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>
    <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
    <div class="input-group input-group-seamless ml-3">
        <div class="input-group-prepend">
        <div class="input-group-text">
            <!-- <i class="fas fa-search"></i> -->
        </div>
        </div>
        <input style="visibility:hidden" class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search"> </div>
    </form>
    <div class="nav-wrapper">
        <ul class="nav flex-column">
            @include('layouts.menu')
        </ul>
    </div>
</aside>